### PR TITLE
Fix importing images and labels with filenames with multiple dots

### LINKED ISSUE #140: Import darknet (aka YOLO) format annotations fails when image/label filenames contain multiple "." characters
**Describe the bug**
I have image files and annotations in a format such as "DSC_0023.mp4#t=22.png" and "DSC_0023.mp4#t=22.txt".  Importing these existing annotations fails with an error message "Given predicate results in more than one value being matched".  

**To Reproduce**
1. select Import Annotations
2. select Multiple Files in YOLO Format
3. Select multiple annotation files in format "DSC_0000.mp4#t=0.txt"
4. Import fails with error "Given predicate results in more than one value being matched"

**Expected behavior**

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 87
 - Version develop/HEAD (afc138d)

**Additional context**
This appears to be the result YOLOImporter.matchImagesWithAnnotations using FileUtils.extractFilename which returns index 0 after splitting the filename on dot (".").  
A proposed fix is extractFilename to return path.basename(name, path.extname(name)) instead of name.split(".")[0]

### PR DESCRIPTION
**Pull request by h3ct0r**
### Pre-flight checklist

- [X] Unit tests for all non-trivial changes
- [X] Tested locally
- [ ] Updated wiki no need

Labels and filenames with multiple dots now are working as intended, fix #140.

### CODE REVIEW

**Comment by SkalskiP** [comment]
Hi @h3ct0r :) Thank you for that PR. Looks good. Please remove comments and we can merge. ;)

File: src/utils/FileUtil.ts [hunk 1]
```diff
@@ -42,10 +42,20 @@ export class FileUtil {
 
     public static extractFileExtension(name: string): string | null {
         const parts = name.split(".");
-        return parts.length > 1 ? parts[1] : null;
+        //return parts.length > 1 ? parts[1] : null;
+        // fix for files with multiple dots
```
Comment (SkalskiP) [inline src/utils/FileUtil.ts:46]:
```suggestion
```

File: src/utils/FileUtil.ts [hunk 2]
```diff
@@ -42,10 +42,20 @@ export class FileUtil {
...
+        return parts.length > 1 ? parts[parts.length - 1] : null;
     }
 
     public static extractFileName(name: string): string | null {
-        return name.split(".")[0];
+        //return name.split(".")[0];
+        // fix for files with multiple dots
```
Comment (SkalskiP) [inline src/utils/FileUtil.ts:52]:
```suggestion
```

**Review by SkalskiP — CHANGES_REQUESTED** [review]

File: src/utils/FileUtil.ts (hunk 1 above)
Comment (h3ct0r) [reply src/utils/FileUtil.ts]: Comments were removed

File: src/utils/FileUtil.ts (hunk 2 above)
Comment (h3ct0r) [reply src/utils/FileUtil.ts]: Comments were removed

**Comment by h3ct0r** [comment]
> Hi @h3ct0r :) Thank you for that PR. Looks good. Please remove comments from your code and we can merge. ;)

Hi @SkalskiP, sure! the comments are now removed! If you need another change please let me know.

**Comment by SkalskiP** [comment]
Thank you very much. @h3ct0r I know it may be to much to ask, but would it be possible to add some unit tests for those two functions?

**Comment by h3ct0r** [comment]
> Thank you very much. @h3ct0r I know it may be to much to ask, but would it be possible to add some unit tests for those two functions?

Sure, unit test were added

**Comment by SkalskiP** [comment]
Hi @h3ct0r! Thank you very much for your contribution. We are merging that PR into `develop`. Regards ;)
